### ISSUE TITLE
Crashes with Ears Mod

### ISSUE THREAD

**Issue by fennecr** [Creatomat/Better-Animations#28]
Crashes when entering third person while using the Ears mod.

`---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-06-17 23:13:46
Description: Rendering entity in world

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:680)
	at net.minecraft.class_630.method_22700(class_630.java:181)
	at com.unascribed.ears.EarsFeatureRenderer$1.doAnchorTo(EarsFeatureRenderer.java:98)
	at com.unascribed.ears.EarsFeatureRenderer$1.doAnchorTo(EarsFeatureRenderer.java:82)
	at com.unascribed.ears.common.render.AbstractEarsRenderDelegate.anchorTo(AbstractEarsRenderDelegate.java:106)
	at com.unascribed.ears.common.EarsRenderer.renderInner(EarsRenderer.java:154)
	at com.unascribed.ears.common.EarsRenderer.render(EarsRenderer.java:63)
	at com.unascribed.ears.common.EarsCommon.render(EarsCommon.java:142)
	at com.unascribed.ears.common.render.IndirectEarsRenderDelegate.render(IndirectEarsRenderDelegate.java:35)
	at com.unascribed.ears.common.render.IndirectEarsRenderDelegate.render(IndirectEarsRenderDelegate.java:23)
	at com.unascribed.ears.EarsFeatureRenderer.render(EarsFeatureRenderer.java:71)
	at com.unascribed.ears.EarsFeatureRenderer.method_4199(EarsFeatureRenderer.java:58)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_1007.method_4215(class_1007.java:66)
	at net.minecraft.class_1007.method_3936(class_1007.java:43)
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.method_22710(class_761.java:1324)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)`

**Comment by Creatomat** [comment]
This is an issue while using custom animations with emf, I cannot fix it
